baseURL: https://blog.cloudfright.com
languageCode: en-us
title: Cloudfright
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

menu: 
  main:
    - name: Search
      url: /search/
      weight: 1
    - name: Categories
      url: /categories/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10
    - name: Series
      url: /series/
      weight: 15
    - name: Archive
      url: archives/
      weight: 20
    - name: About Me
      url: /about/whoami/
      weight: 25
    - name: Privacy
      url: /privacy/
      weight: 30
  
outputs:
    home:
        - HTML
        - RSS
        - JSON 

taxonomies:
    category: categories
    tag: tags
    series: series

params:
  env: production
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true


  homeInfoParams:
        Title: "Blog"
        Content: >      
          Posts on software engineering,  learning, behavioural science, music production, maths and science. 
          If you'd like to get in touch, DM on me Twitter. Please be kind. I like kind people. 

  socialIcons:
    - name: github
      url: "https://github.com/cloudfright"
    - name: twitter
      url: "https://twitter.com/cloudfright"
    - name: linkedin
      url: https://www.linkedin.com/in/ben-dyer-5aa7414/
