baseURL: https://blog.cloudfright.com
languageCode: en-us
title: Cloudfright
theme: PaperMod

enableRobotsTXT: true
googleAnalytics: UA-65290098-1

menu: 
  main:
    - name: About Me
      url: /about/whoami/
      weight: 1
    - name: Archive
      url: archives/
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags
      weight: 15
    - name: Categories
      url: categories
      weight: 20
  
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

taxonomies:
    category: categories
    tag: tags
    series: series

params:
  env: production
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true


  homeInfoParams:
        Title: "Blog"
        Content: >      
          Posts on software engineering,  learning, psychology, music production, maths and science. 
          If you'd like to get in touch, DM on me Twitter. Please be kind. I like kind people. 

  socialIcons:
    - name: github
      url: "https://github.com/cloudfright"
    - name: twitter
      url: "https://twitter.com/cloudfright"
    - name: linkedin
      url: https://www.linkedin.com/in/ben-dyer-5aa7414/
  
  analytics:
      google:
          SiteVerificationTag: "UA-65290098-1"


# https://adityatelange.github.io/hugo-PaperMod/
# https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite
# https://docs.microsoft.com/en-us/azure/static-web-apps/publish-hugo
# https://ruddra.com/hugo-deploy-static-page-using-github-actions/